"""Builds js/data/vectors.js: all-MiniLM-L6-v2 vectors for the vector search (RN.vsearch).

    node tools/export-search-corpus.js corpus.json
    python tools/build_vectors.py corpus.json

Embeds one document per operator, every focus area, every role category, and every word that
appears in them (so a free-text query can be turned into a vector in the browser). Vectors are
L2-normalised and stored as int8 (x127) in one base64 blob per kind. Needs the nomad-match
virtualenv (fastembed): ../../nomad-match/.venv/bin/python tools/build_vectors.py corpus.json
"""
import base64
import json
import math
import re
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[3] / "nomad-match"))
from nomad_match import embeddings as E  # noqa: E402

STOP = set("a an the and or of to for in on with at by from is are was were be been it its this that these those we our us you your i me my they them their he she his her as but not no so if than then too very can just about into over under up down out more most less only also all any each every some such own same other new using use used get got have has had do does did will would should could".split())


def tokens(s):
    return [w for w in re.findall(r"[a-z][a-z0-9+&'-]*", s.lower()) if w not in STOP and len(w) > 1]


def pack(vecs):
    q = np.clip(np.round(np.asarray(vecs, dtype=np.float32) * 127), -127, 127).astype(np.int8)
    return base64.b64encode(q.tobytes()).decode()


def main(path):
    C = json.loads(Path(path).read_text())
    docs = [tokens(o["text"]) for o in C["ops"]] + [tokens(t["text"]) for t in C["tags"]]
    df = {}
    for d in docs:
        for w in set(d):
            df[w] = df.get(w, 0) + 1
    words = sorted(df)
    n = len(docs)
    idf = [round(math.log((n + 1) / (df[w] + 1)) + 1, 3) for w in words]
    out = {
        "dim": 384,
        "ops": {"ids": [o["id"] for o in C["ops"]], "v": pack(E.embed([o["text"] for o in C["ops"]]))},
        "tags": {"names": [t["v"] for t in C["tags"]], "v": pack(E.embed([t["text"] for t in C["tags"]]))},
        "cats": {"keys": [c["k"] for c in C["cats"]], "v": pack(E.embed([c["text"] for c in C["cats"]]))},
        "words": {"w": words, "idf": idf, "v": pack(E.embed(words))},
        "stop": sorted(STOP),
    }
    dest = Path(__file__).resolve().parent.parent / "js" / "data" / "vectors.js"
    dest.write_text("/* Generated by tools/build_vectors.py: all-MiniLM-L6-v2 vectors (int8) for RN.vsearch. Do not edit. */\n"
                    "window.RN = window.RN || {}; RN.data = RN.data || {};\nRN.data.vectors = " + json.dumps(out, separators=(",", ":")) + ";\n")
    print(f"ops {len(C['ops'])} tags {len(C['tags'])} words {len(words)} -> {dest} ({dest.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main(sys.argv[1])
